alter table public.profiles add column if not exists show_in_explore boolean not null default true;

create table if not exists public.blocks (
  blocker_id uuid not null references auth.users(id) on delete cascade,
  blocked_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  check (blocker_id <> blocked_id)
);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  reported_id uuid not null references auth.users(id) on delete cascade,
  reason text not null,
  created_at timestamptz not null default now(),
  check (reporter_id <> reported_id)
);

alter table public.blocks enable row level security;
alter table public.reports enable row level security;

drop policy if exists blocks_select_own on public.blocks;
drop policy if exists blocks_insert_own on public.blocks;
drop policy if exists blocks_delete_own on public.blocks;
create policy blocks_select_own on public.blocks for select using (blocker_id = auth.uid());
create policy blocks_insert_own on public.blocks for insert with check (blocker_id = auth.uid());
create policy blocks_delete_own on public.blocks for delete using (blocker_id = auth.uid());

drop policy if exists reports_insert_own on public.reports;
create policy reports_insert_own on public.reports for insert with check (reporter_id = auth.uid());

-- Prevent users from changing another user's visibility setting.
-- Existing profiles_update_own already limits updates to the signed-in user's row.
